### ISSUE TITLE
Support Microsoft.Data.SqlClient for Tanneryd.BulkOperations.EF6

### ISSUE THREAD

**Issue by zane-woodard-drc** [mtanneryd/ef-bulk-operations#42]
With the release of Entity Framework 6.5, the Microsoft.Data.SqlClient provider can be through the Microsoft.EntityFramework.SqlServer package. However, wrapping EF6.5 to use the better supported SQL provider makes it incompatible with the existing Tanneryd.BulkOperations.EF6.

After completing the migration described by the Microsoft.EntityFramework.SqlServer README, Tanneryd.BulkOperations.EF6 began throwing this exception:

Message: Unable to cast object of type 'Microsoft.Data.SqlClient.SqlConnection' to type 'System.Data.SqlClient.SqlConnection'.
TARGETSITE: System.Data.SqlClient.SqlConnection GetSqlConnection(System.Data.Entity.DbContext)
STACKTRACE:    at Tanneryd.BulkOperations.EF6.DbContextExtensions.GetSqlConnection(DbContext ctx)
   at Tanneryd.BulkOperations.EF6.DbContextExtensions.GetClusteredIndexColumns(DbContext ctx, String schema, String tableName, SqlTransaction sqlTransaction, Mappings mappings)
   at Tanneryd.BulkOperations.EF6.DbContextExtensions.BulkInsertAll[T](DbContext ctx, BulkInsertRequest`1 request)
   at Tanneryd.BulkOperations.EF6.DbContextExtensions.BulkInsertAll[T](DbContext ctx, IList`1 entities, SqlTransaction transaction, Boolean recursive)

**Comment by mtanneryd** [comment]
Thanks for the feedback. I will look into this as soon as I can.Måns TånnerydTånneryd IT ABBarrskogsvägen 1918653 Vallentuna+46-705140093https://se.linkedin.com/in/manstanneryd10 juni 2024 kl. 23:55 skrev zane-woodard-drc ***@***.***>:﻿
With the release of Entity Framework 6.5, the Microsoft.Data.SqlClient provider can be through the Microsoft.EntityFramework.SqlServer package. However, wrapping EF6.5 to use the better supported SQL provider makes it incompatible with the existing Tanneryd.BulkOperations.EF6.
After completing the migration described by the Microsoft.EntityFramework.SqlServer README, Tanneryd.BulkOperations.EF6 began throwing this exception:
Message: Unable to cast object of type 'Microsoft.Data.SqlClient.SqlConnection' to type 'System.Data.SqlClient.SqlConnection'.
TARGETSITE: System.Data.SqlClient.SqlConnection GetSqlConnection(System.Data.Entity.DbContext)
STACKTRACE:    at Tanneryd.BulkOperations.EF6.DbContextExtensions.GetSqlConnection(DbContext ctx)
at Tanneryd.BulkOperations.EF6.DbContextExtensions.GetClusteredIndexColumns(DbContext ctx, String schema, String tableName, SqlTransaction sqlTransaction, Mappings mappings)
at Tanneryd.BulkOperations.EF6.DbContextExtensions.BulkInsertAll[T](DbContext ctx, BulkInsertRequest1 request) at Tanneryd.BulkOperations.EF6.DbContextExtensions.BulkInsertAll[T](DbContext ctx, IList1 entities, SqlTransaction transaction, Boolean recursive)

**Comment by mtanneryd** [comment]
Hi!

I can see at https://learn.microsoft.com/en-us/ef/ef6/what-is-new/ that they claim to have been releasing EF 6.5.0 to nuget in June but I cannot find the actual nuget package at nuget.org. Have you installed a preview?

**Comment by zane-woodard-drc** [comment]
Yea, full version id is [6.5.0-preview2-24180-01](https://www.nuget.org/packages/EntityFramework/6.5.0-preview2-24180-01)

The 6.5 release has been in a strange state for awhile, but docs are starting to be updated so I'd guess it's leaving preview soon.

**Comment by mtanneryd** [comment]
Version 2.1.0 is now using EF 6.5.1 and I tried running the tests in Tanneryd.BulkOperations.EF6.NET47.Tests using the new MicrosoftSqlDbConfiguration but everything seems to work just fine. Can you still reproduce the issue using 2.1.0?

**Comment by zane-woodard-drc** [comment]
Yea, updated to EF 6.5.1 this morning and still seeing the issue. I see your recent commit to upgrade to EF 6.5.1, did you also switch to Microsoft.Data.SqlClient in the test project?

EF6.5 doesn't force a switch to Microsoft.Data.SqlClient, but support for Microsoft.Data.SqlClient is one of its biggest changes. Guide for switching with EF6.5 is here:
https://learn.microsoft.com/en-us/ef/ef6/what-is-new/microsoft-ef6-sqlserver

**Comment by mtanneryd** [comment]
I did force the switch in the test project actually  and had no problems running the tests. The current version on github does not force the switch though. 

When testing it I used the following attribute on the context class:
[DbConfigurationType(typeof(MicrosoftSqlDbConfiguration))]

**Comment by mtanneryd** [comment]
Hmm, I might have missed some additional required code changes. I’ll give it another try later. Watching France vs Portugal in the UEFA EURO 2024.

**Comment by kirmak** [comment]
Actually, you will have to use Microsoft.Data.SqlClient instead of System.Data.SqlClient namespaces everywhere. I did the change, there are 7 changes and it works well. The isue is that it will work only on net8 and net48 targets. And it should be separate nuget package as code base differs.

I've tried to make changes to make pull request, but there are few questions )
1. I could make conditional properties in project files and conditional usings in the code - it looks a bit complicated, but no need to duplicate whole code.
2. Make third folder near Tanneryd.BulkOperations.EF6 and Tanneryd.BulkOperations.EFCore, copy ...EF6 code and target to net8. Then we could use new name for project and namespace.

**Comment by kirmak** [comment]
I've made a PR to discuss changes needed https://github.com/mtanneryd/ef-bulk-operations/pull/43

**Comment by mtanneryd** [comment]
Thanks, been a bit busy but will have a look again soon.Måns TånnerydTånneryd IT ABBarrskogsvägen 19186 53 Vallentuna+46-705140093https://se.linkedin.com/in/manstanneryd11 feb. 2025 kl. 14:22 skrev Kirill Lukianenko ***@***.***>:﻿
I've made a PR to discuss changes needed #43

**Comment by mtanneryd** [comment]
> With the release of Entity Framework 6.5, the Microsoft.Data.SqlClient provider can be through the Microsoft.EntityFramework.SqlServer package. However, wrapping EF6.5 to use the better supported SQL provider makes it incompatible with the existing Tanneryd.BulkOperations.EF6.
> 
> After completing the migration described by the Microsoft.EntityFramework.SqlServer README, Tanneryd.BulkOperations.EF6 began throwing this exception:
> 
> ```
> Message: Unable to cast object of type 'Microsoft.Data.SqlClient.SqlConnection' to type 'System.Data.SqlClient.SqlConnection'.
> TARGETSITE: System.Data.SqlClient.SqlConnection GetSqlConnection(System.Data.Entity.DbContext)
> STACKTRACE:    at Tanneryd.BulkOperations.EF6.DbContextExtensions.GetSqlConnection(DbContext ctx)
>    at Tanneryd.BulkOperations.EF6.DbContextExtensions.GetClusteredIndexColumns(DbContext ctx, String schema, String tableName, SqlTransaction sqlTransaction, Mappings mappings)
>    at Tanneryd.BulkOperations.EF6.DbContextExtensions.BulkInsertAll[T](DbContext ctx, BulkInsertRequest`1 request)
>    at Tanneryd.BulkOperations.EF6.DbContextExtensions.BulkInsertAll[T](DbContext ctx, IList`1 entities, SqlTransaction transaction, Boolean recursive)
> ```

There is a new version in the repo, v3.0.0 (no published packages). It seems to work fine with EF 6.5.1 and Microsoft.Data.SqlClient.

**Comment by OldWarrior3000** [comment]
Hey @mtanneryd ,Do you have any ETA when you could publish the changes as Nuget package. I am just running into the same problem. Thanks!

**Comment by mtanneryd** [comment]
> Hey [@mtanneryd](https://github.com/mtanneryd) ,Do you have any ETA when you could publish the changes as Nuget package. I am just running into the same problem. Thanks!

Version 3.0.1 has been uploaded to nuget.org. Hopefully it will work as expected. I'm not using the EF6 packages much myself anymore since our systems are moving away from EF6 to EFCore and NET10.0.

**Comment by OldWarrior3000** [comment]
@mtanneryd , thank a lot you for the quick response and publising. It worked for me so far!
